# Generated by Django 5.0.2 on 2024-02-21 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=32)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_curl_pattern', models.CharField(choices=[('curly', 'Curly'), ('straight', 'Straight')], max_length=16)),
                ('original_density', models.IntegerField(help_text='Density of the wig in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('original_hair_origin', models.CharField(choices=[('brazilian', 'Brazilian'), ('peruvian', 'Peruvian')], max_length=16)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_color', models.CharField(blank=True, max_length=32, null=True)),
                ('custom_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_curl_pattern', models.CharField(blank=True, choices=[('curly', 'Curly'), ('straight', 'Straight')], max_length=16, null=True)),
                ('custom_density', models.IntegerField(blank=True, help_text='Density of the wig in percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('custom_hair_origin', models.CharField(blank=True, choices=[('brazilian', 'Brazilian'), ('peruvian', 'Peruvian')], max_length=16, null=True)),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
