# Generated by Django 5.0.2 on 2024-02-21 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wig',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wig',
            name='custom_density',
            field=models.IntegerField(blank=True, help_text='Density of the wig in percentage (0-300%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
