# Generated by Django 5.0.2 on 2024-02-21 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wigs', '0002_wig_is_custom_alter_wig_custom_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wig',
            name='original_density',
            field=models.IntegerField(blank=True, help_text='Density of the wig in percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
