# docker-compose.yml
version: '3'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        environment: 
        #should be in a .env in the future
            - DJANGO_SETTINGS_MODULE=wigs_project.settings
            - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

volumes:
  postgres_data:
