# docker-compose.yml
version: '3'

services:
    web:
        build: .
        command: gunicorn wigs_project.wsgi:application -w 4 --log-level debug
        volumes:
            - .:/code
        ports:
            - 8000:8000  

    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres

volumes:
  postgres_data:
