# docker-compose.yml


services:
    web:
        build: .
        command: gunicorn wigs_project.wsgi:application --bind 0.0.0.0:8000 --workers 4

        volumes:
            - .:/code
        ports:
            - 8000:8000  

#     db:
#         image: postgres:14
#         volumes:
#             - postgres_data:/var/lib/postgresql/data/
#             - ./path/to/custom-config:/var/lib/postgresql/data/  # Add this line for custom config
#         environment:
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: postgres
#             POSTGRES_DB: postgres
#         command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]  # Add this line for custom config

# volumes:
#   postgres_data:

